### ISSUE TITLE
Import into Android Studio

### ISSUE THREAD

**Issue by toddy15** [rigid/Birthdroid#17]
Hi,

I'd like to suggest to import this project into Android Studio, as that is the new recommended IDE for building android apps (see links).

https://developer.android.com/sdk/installing/migrate.html
https://developer.android.com/tools/studio/eclipse-transition-guide.html

I've done this already, if you'd like, I can create a pull request to include the necessary changes. You can take a look at the changes here:

https://github.com/toddy15/Birthdroid/tree/import-in-android-studio

The app builds fine with Android Studio/Gradle on my computer.

**Comment by rigid** [comment]
if you could keep the existing Makefile intact for now, I'd love to merge a pull-request. Thanks!

**Comment by toddy15** [comment]
Hm, apart from being the recommended IDE for Android development, the main reason for switching to Android Studio was for me that I couldn't get the app to build with the Makefile. Therefore, I don't know if I'm able to provide a working Makefile.

However, the move to Android Studio resulted in a switch of build systems. The eclipse/ant system is no longer used by Android Studio, instead, they use gradle.

One side effect is that the source paths are different, so keeping the Makefile seems rather difficult to me.

Did you try Android Studio yet? Or do you need the Makefile for other purposes?

**Comment by rigid** [comment]
if you could just leave the file intact for now i'd test if everything works. The Makefile will surely be removed in the future.
I just used it to wrap the manual build so I don't need an IDE to build.

**Comment by toddy15** [comment]
Well, you can still build the apk manually, without installing or using the IDE. Just use the "gradlew" wrapper script on the command line (or gradlew.bat if you're on Windows). That is essentially what the IDE uses as well behind the scenes.

On the first run, it'll download the gradle scripts for execution. You'll need to tell gradle where your Android SDK is installed, in a file called "local.properties" in the root directory of the project with one line in it:

sdk.dir=/home/rigid/android-sdk (or similar)

That should do the trick.

**Comment by toddy15** [comment]
Hi,

did you have the time to review this issue?

**Comment by rigid** [comment]
hi, 
sadly, not. But i'll merge it if you could send a pull request. It would be nice if you could send one.

**Comment by toddy15** [comment]
Thanks for merging!
